In [ ]:
torch.randn(4, 4)

NameError: name 'torch' is not defined

In [ ]:
import torch

In [ ]:
torch.randn(4, 4)

tensor([[-0.4541,  0.7704,  0.7560, -0.3651],
        [ 0.6689,  0.0406, -0.7767,  1.1087],
        [ 0.7236, -1.8391,  0.1516, -1.6256],
        [-2.3129, -0.3234,  0.2430, -1.1343]])

In [ ]:
a = torch.randn(4, 4)

In [ ]:
torch.mean(a)

tensor(-0.2610)

In [ ]:
torch.mean(a, 0)

tensor([ 0.3686, -0.8157, -0.3212, -0.2757])

In [ ]:
torch.mean(a, 0, keepdim = True)

tensor([[ 0.3686, -0.8157, -0.3212, -0.2757]])

In [ ]:
a

tensor([[ 0.3228, -0.8105, -0.5150,  0.5570],
        [ 1.2147, -0.0608, -0.9249, -0.5291],
        [ 0.0893, -1.5286,  0.5906, -0.1457],
        [-0.1526, -0.8628, -0.4355, -0.9849]])

In [ ]:
torch.mean(a, 1, keepdim = True)

tensor([[-0.1114],
        [-0.0750],
        [-0.2486],
        [-0.6089]])

In [ ]:
a - torch.mean(a, 1, keepdim = True)

tensor([[ 0.4342, -0.6991, -0.4035,  0.6684],
        [ 1.2898,  0.0142, -0.8499, -0.4541],
        [ 0.3379, -1.2800,  0.8392,  0.1029],
        [ 0.4564, -0.2538,  0.1734, -0.3760]])

In [ ]:
a**2

tensor([[0.1042, 0.6569, 0.2652, 0.3103],
        [1.4756, 0.0037, 0.8555, 0.2800],
        [0.0080, 2.3367, 0.3488, 0.0212],
        [0.0233, 0.7444, 0.1897, 0.9701]])

In [ ]:
torch.sqrt(torch.mean(a**2, 1, keepdim = True))

tensor([[0.5780],
        [0.8085],
        [0.8238],
        [0.6942]])

In [ ]:
def _norm(self, x):
        """
        Compute the root mean square normalization. Use Equation 4 under
        Section 4 of https://arxiv.org/abs/1910.07467 as a reference. Add 
        the given epsilon value (self.eps) to the tensor's norm (i.e. inside
        the square root in Equation 4) before normalizing the tensor.

        Args:
            x (torch.Tensor): The input tensor.

        Returns:
            torch.Tensor: The normalized tensor.
        """
        xmean = torch.mean(x, 1, keepdim = True)
        rms = torch.sqrt(torch.mean(x**2, 1, keepdim = True))

        x_norm = (x-xmean)/(rms+self.eps)

        return x_norm


In [ ]:
def _norm(x):
        """
        Compute the root mean square normalization. Use Equation 4 under
        Section 4 of https://arxiv.org/abs/1910.07467 as a reference. Add 
        the given epsilon value (self.eps) to the tensor's norm (i.e. inside
        the square root in Equation 4) before normalizing the tensor.

        Args:
            x (torch.Tensor): The input tensor.

        Returns:
            torch.Tensor: The normalized tensor.
        """
        xmean = torch.mean(x, 1, keepdim = True)
        rms = torch.sqrt(torch.mean(x**2, 1, keepdim = True))

        x_norm = (x-xmean)/(rms+1e-6)

        return x_norm


In [ ]:
a

tensor([[ 0.3228, -0.8105, -0.5150,  0.5570],
        [ 1.2147, -0.0608, -0.9249, -0.5291],
        [ 0.0893, -1.5286,  0.5906, -0.1457],
        [-0.1526, -0.8628, -0.4355, -0.9849]])

In [ ]:
_norm(a)

tensor([[ 0.7511, -1.2094, -0.6981,  1.1564],
        [ 1.5952,  0.0176, -1.0512, -0.5616],
        [ 0.4102, -1.5538,  1.0187,  0.1249],
        [ 0.6575, -0.3657,  0.2498, -0.5416]])

In [ ]:
def _norm(x):
        """
        Compute the root mean square normalization. Use Equation 4 under
        Section 4 of https://arxiv.org/abs/1910.07467 as a reference. Add 
        the given epsilon value (self.eps) to the tensor's norm (i.e. inside
        the square root in Equation 4) before normalizing the tensor.

        Args:
            x (torch.Tensor): The input tensor.

        Returns:
            torch.Tensor: The normalized tensor.
        """
        xmean = torch.mean(x, 1, keepdim = True)
        rms = torch.sqrt(torch.mean(x**2, -11, keepdim = True))

        x_norm = (x-xmean)/(rms+1e-6)

        return x_norm


In [ ]:
_norm(a)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got -11)

In [ ]:
def _norm(x):
        """
        Compute the root mean square normalization. Use Equation 4 under
        Section 4 of https://arxiv.org/abs/1910.07467 as a reference. Add 
        the given epsilon value (self.eps) to the tensor's norm (i.e. inside
        the square root in Equation 4) before normalizing the tensor.

        Args:
            x (torch.Tensor): The input tensor.

        Returns:
            torch.Tensor: The normalized tensor.
        """
        xmean = torch.mean(x, 1, keepdim = True)
        rms = torch.sqrt(torch.mean(x**2, -1, keepdim = True))

        x_norm = (x-xmean)/(rms+1e-6)

        return x_norm


In [ ]:
_norm(a)

tensor([[ 0.7511, -1.2094, -0.6981,  1.1564],
        [ 1.5952,  0.0176, -1.0512, -0.5616],
        [ 0.4102, -1.5538,  1.0187,  0.1249],
        [ 0.6575, -0.3657,  0.2498, -0.5416]])

In [ ]:
a= torch.tensor([[1, 2, 3], [-1, 0, 1]])

In [ ]:
_norm(a)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
a= torch.tensor([[1, 2, 3], [-1, 0, 1]], dtype=torch.float64)

In [ ]:
_norm(a)

tensor([[-0.4629,  0.0000,  0.4629],
        [-1.2247,  0.0000,  1.2247]], dtype=torch.float64)

In [ ]:
a= torch.tensor([[1, 2, 3, 0], [-2, 0, 2,0]], dtype=torch.float64)

In [ ]:
_norm(a)

tensor([[-0.2673,  0.2673,  0.8018, -0.8018],
        [-1.4142,  0.0000,  1.4142,  0.0000]], dtype=torch.float64)

In [ ]:
a= torch.tensor([[1, 2, 3, 0], [-2, -2, 2,2]], dtype=torch.float64)

In [ ]:
_norm(a)

tensor([[-0.2673,  0.2673,  0.8018, -0.8018],
        [-1.0000, -1.0000,  1.0000,  1.0000]], dtype=torch.float64)

In [ ]:
a

tensor([[ 1.,  2.,  3.,  0.],
        [-2., -2.,  2.,  2.]], dtype=torch.float64)

In [ ]:
seq_len = 4

In [ ]:
head_dim = 3